  architecture: standalone
  auth:
    enabled: false
  commonConfiguration: |-
    maxmemory 512mb
    maxmemory-policy allkeys-lru
    stop-writes-on-bgsave-error no
  master:
    revisionHistoryLimit: 2
    disableCommands: []
    resources:
      limits:
        cpu: '2'
        memory: 512Mi
        ephemeral-storage: 2Gi
      requests:
        cpu: 10m
        memory: 512Mi
        ephemeral-storage: 50Mi
    persistence:
      enabled: true
      storageClass: longhorn
      size: 1Gi
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
    resources:
      limits:
        cpu: '2'
        memory: 128Mi
        ephemeral-storage: 2Gi
      requests:
        cpu: 10m
        memory: 32Mi
        ephemeral-storage: 50Mi
