apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.cluster17.fullnameOverride }}-backup-s3-creds
  labels:
    cnpg.io/reload: "true"
    {{- include "gia.labels" (dict "context" . "component" "cnpg" "name" "cnpg") | nindent 4 }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
          {{- include "gia.labels" (dict "context" . "component" "cnpg" "name" "cnpg") | nindent 10 }}
      data:
        ACCESS_KEY_ID: {{ `"{{ .accessKeyId }}"` }}
        ACCESS_SECRET_KEY: {{ `"{{ .accessSecretKey }}"` }}
  data:
    - secretKey: accessKeyId
      remoteRef:
        key: secret/gia
        property: backup-access-key-id
    - secretKey: accessSecretKey
      remoteRef:
        key: secret/gia
        property: backup-access-secret-key
