apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "gia.api.fullname" . }}
  labels:
    {{- include "gia.labels" (dict "context" . "component" .Values.api.name "name" .Values.api.name) | nindent 4 }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      {{- include "gia.selectorLabels" (dict "context" . "name" .Values.api.name) | nindent 6 }}
  template:
    metadata:
      {{- with .Values.global.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "gia.labels" (dict "context" . "component" .Values.api.name "name" .Values.api.name) | nindent 8 }}
        app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.global.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.api.name }}
          securityContext:
            {{- toYaml .Values.global.securityContext | nindent 12 }}
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ default .Values.global.imagePullPolicy .Values.api.image.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.api.containerPort }}
              protocol: TCP
          {{- with .Values.api.env }}
          env: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.api.envFrom }}
          envFrom: {{- toYaml . | nindent 12 }}
          {{- end }}
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          volumeMounts:
          - mountPath: /tmp
            name: tmp
      volumes:
      - name: tmp
        emptyDir:
          medium: Memory
      {{- with .Values.api.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
