apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: secret-env
  labels:
    {{- include "gia.labels" (dict "context" . "component" .Values.api.name "name" .Values.api.name) | nindent 4 }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    template:
      engineVersion: v2
      metadata:
        labels:
          {{- include "gia.labels" (dict "context" . "component" .Values.api.name "name" .Values.api.name) | nindent 10 }}
      data:
        POSTGRES_PASSWORD: {{` "{{ .postgresPassword }}" `}}
        POSTGRES_USER_PASSWORD: {{` "{{ .postgresUserPassword }}" `}}
        DJANGO_SECRET_KEY: {{` "{{ .djangoSecretKey }}" `}}
        DJANGO_EMAIL_HOST: {{` "{{ .djangoEmailHost }}" `}}
        DJANGO_EMAIL_PORT: {{` "{{ .djangoEmailPort }}" `}}
        DJANGO_EMAIL_HOST_USER: {{` "{{ .djangoEmailHostUser }}" `}}
        DJANGO_EMAIL_HOST_PASSWORD: {{` "{{ .djangoEmailHostPassword }}" `}}
        OTEL_TRACING_ENABLED: {{` "{{ .otelTracingEnabled }}" `}}
        OTEL_EXPORTER_OTLP_ENDPOINT: {{` "{{ .otelExporterOtlpEndpoint }}" `}}
  data:
    - secretKey: postgresPassword
      remoteRef:
        key: secret/gia
        property: postgres-password
    - secretKey: postgresUserPassword
      remoteRef:
        key: secret/gia
        property: postgres-user-password
    - secretKey: djangoSecretKey
      remoteRef:
        key: secret/gia
        property: django-secret-key
    - secretKey: djangoEmailHost
      remoteRef:
        key: secret/common/smtp
        property: host
    - secretKey: djangoEmailPort
      remoteRef:
        key: secret/common/smtp
        property: port
    - secretKey: djangoEmailHostUser
      remoteRef:
        key: secret/common/smtp
        property: username
    - secretKey: djangoEmailHostPassword
      remoteRef:
        key: secret/common/smtp
        property: password
    - secretKey: otelTracingEnabled
      remoteRef:
        key: secret/gia-otel
        property: otel-tracing-enabled
    - secretKey: otelExporterOtlpEndpoint
      remoteRef:
        key: secret/gia-otel
        property: otel-exporter-otlp-endpoint
