apiVersion: v1
kind: Service
metadata:
  name: {{ template "gia.api.fullname" . }}
  labels:
    {{- include "gia.labels" (dict "context" . "component" .Values.api.name "name" .Values.api.name) | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "gia.selectorLabels" (dict "context" . "name" .Values.api.name) | nindent 4 }}
