apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: secret-env
  labels:
    {{- include "samgrabby.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    template:
      engineVersion: v2
      metadata:
        labels:
          {{- include "samgrabby.labels" . | nindent 10 }}
      data:
        DJANGO_SECRET_KEY: {{` "{{ .djangoSecretKey }}" `}}
  data:
    - secretKey: djangoSecretKey
      remoteRef:
        key: secret/samgrabby
        property: django-secret-key
