replicaCount: 1

nameOverride: ""
fullnameOverride: ""

image:
  repository: git.devmem.ru/projects/samgrabby
  tag: ""
  pullPolicy: Always
containerPort: 5000

imagePullSecrets:
  - name: regcred

env:
  - name: POD_IP
    valueFrom:
      fieldRef:
        fieldPath: status.podIP
  - name: TZ
    value: "Europe/Moscow"
  - name: DJANGO_SETTINGS_MODULE
    value: "config.settings.production"
  - name: DJANGO_ALLOWED_HOSTS
    value: "soft.devmem.ru"

envFrom:
  - secretRef:
      name: secret-env
  # - configMapRef:
  #     name: cm

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: &host soft.devmem.ru
      paths:
        - path: /
  tls:
    - hosts:
        - *host
      secretName: soft-tls

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  # limits:
  #   cpu: 200m
  #   memory: 512Mi

podAnnotations: {}
podSecurityContext: {}
  # fsGroup: 1000
securityContext: {}
  # capabilities:
  #   drop:
  #     - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000
nodeSelector: {}
tolerations: []
affinity: {}
