{{- if .Values.pgbackrest.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pgbackrest
  labels:
    {{- include "gia.labels" (dict "context" . "component" .Values.pgbackrest.name "name" .Values.pgbackrest.name) | nindent 4 }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    template:
      engineVersion: v2
      metadata:
        labels:
          {{- include "gia.labels" (dict "context" . "component" .Values.pgbackrest.name "name" .Values.pgbackrest.name) | nindent 10 }}
      data:
        PGBACKREST_STANZA: "gia"
        PGBACKREST_PG1_PATH: "/bitnami/postgresql/data"
        PGBACKREST_LOG_LEVEL_CONSOLE: "info"
        PGBACKREST_LOG_LEVEL_FILE: "off"
        PGBACKREST_LOG_LEVEL_STDERR: "off"
        PGBACKREST_PROCESS_MAX: "4"
        PGBACKREST_COMPRESS_LEVEL: "9"
        PGBACKREST_START_FAST: "y"
        PGBACKREST_DELTA: "y"
        PGBACKREST_REPO1_RETENTION_DIFF: "3"
        PGBACKREST_REPO1_RETENTION_FULL: "28"
        PGBACKREST_REPO1_RETENTION_FULL_TYPE: "time"
        PGBACKREST_REPO1_BUNDLE: "y"
        PGBACKREST_REPO1_TYPE: "s3"
        PGBACKREST_REPO1_PATH: "/pgbackrest"
        PGBACKREST_REPO1_S3_URI_STYLE: "path"
        PGBACKREST_REPO1_S3_KEY: {{` "{{ .pgbackrestS3Key }}" `}}
        PGBACKREST_REPO1_S3_KEY_SECRET: {{` "{{ .pgbackrestS3KeySecret }}" `}}
        PGBACKREST_REPO1_S3_ENDPOINT: {{` "{{ .pgbackrestS3Endpoint }}" `}}
        PGBACKREST_REPO1_S3_REGION: {{` "{{ .pgbackrestS3Region }}" `}}
        PGBACKREST_REPO1_S3_BUCKET: {{` "{{ .pgbackrestS3Bucket }}" `}}
  data:
    - secretKey: pgbackrestS3Key
      remoteRef:
        key: secret/gia
        property: pgbackrest-s3-key
    - secretKey: pgbackrestS3KeySecret
      remoteRef:
        key: secret/gia
        property: pgbackrest-s3-key-secret
    - secretKey: pgbackrestS3Endpoint
      remoteRef:
        key: secret/gia
        property: pgbackrest-s3-endpoint
    - secretKey: pgbackrestS3Region
      remoteRef:
        key: secret/gia
        property: pgbackrest-s3-region
    - secretKey: pgbackrestS3Bucket
      remoteRef:
        key: secret/gia
        property: pgbackrest-s3-bucket
{{- end }}
