{{- if .Values.pgbackrest.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "gia.pgbackrest.fullname" . }}
  labels:
    {{- include "gia.labels" (dict "context" . "component" .Values.pgbackrest.name "name" .Values.pgbackrest.name) | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - "pods"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - ""
    resources:
      - "pods/exec"
    verbs:
      - "create"
{{- end }}
