{{- if .Values.pgbackrest.enabled }}
{{- $serviceName := include "gia.pgbackrest.fullname" . -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $serviceName }}
  labels:
    {{- include "gia.labels" (dict "context" . "component" .Values.pgbackrest.name "name" .Values.pgbackrest.name) | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $serviceName }}
subjects:
  - kind: ServiceAccount
    name: {{ $serviceName }}
{{- end }}
