{{- if .Values.pgbackrest.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "gia.pgbackrest.fullname" . }}
  labels:
    {{- include "gia.labels" (dict "context" . "component" .Values.pgbackrest.name "name" .Values.pgbackrest.name) | nindent 4 }}
{{- end }}
