apiVersion: v1
kind: Service
metadata:
  name: {{ template "gia.front.fullname" . }}
  labels:
    {{- include "gia.labels" (dict "context" . "component" .Values.front.name "name" .Values.front.name) | nindent 4 }}
spec:
  type: {{ .Values.front.service.type }}
  ports:
    - port: {{ .Values.front.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "gia.selectorLabels" (dict "context" . "name" .Values.front.name) | nindent 4 }}
